-- Table: public.kobodata_iniciativakobo

-- DROP TABLE IF EXISTS public.kobodata_iniciativakobo;

CREATE TABLE IF NOT EXISTS public.kobodata_iniciativakobo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    relacao_iniciativa text COLLATE pg_catalog."default",
    nome_iniciativa character varying(255) COLLATE pg_catalog."default",
    estado character varying(100) COLLATE pg_catalog."default",
    municipio character varying(100) COLLATE pg_catalog."default",
    regiao_administrativa character varying(100) COLLATE pg_catalog."default",
    endereco_completo boolean,
    rua character varying(255) COLLATE pg_catalog."default",
    numero character varying(20) COLLATE pg_catalog."default",
    complemento character varying(255) COLLATE pg_catalog."default",
    bairro character varying(100) COLLATE pg_catalog."default",
    cep character varying(10) COLLATE pg_catalog."default",
    ponto_referencia text COLLATE pg_catalog."default",
    outros_bairros text COLLATE pg_catalog."default",
    como_acontece jsonb,
    outra_forma_atuacao text COLLATE pg_catalog."default",
    redes_sociais jsonb,
    responsaveis_perifericos character varying COLLATE pg_catalog."default",
    grupo_instituicao_responsavel jsonb NOT NULL,
    cnpj character varying(20) COLLATE pg_catalog."default",
    acessou_recursos boolean,
    tipos_recursos jsonb,
    outras_fontes text COLLATE pg_catalog."default",
    atua_em_rede boolean,
    parceria_poder_publico boolean,
    temas jsonb,
    equipe_populacoes jsonb,
    publico_alvo jsonb,
    autorizo boolean,
    id_usuario character varying(100) COLLATE pg_catalog."default",
    submission_time timestamp with time zone,
    validation_status character varying(50) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    submitted_by character varying(255) COLLATE pg_catalog."default",
    version character varying(50) COLLATE pg_catalog."default",
    tags character varying(255) COLLATE pg_catalog."default",
    index integer,
    geom geometry(Point,4326),
    outros_definicao_responsavel character varying(255) COLLATE pg_catalog."default",
    cnpj_iniciativa character varying COLLATE pg_catalog."default",
    outras_equipes_pop text COLLATE pg_catalog."default",
    outros_publicos_alvo text COLLATE pg_catalog."default",
    outros_temas text COLLATE pg_catalog."default",
    CONSTRAINT kobodata_iniciativa_pkey PRIMARY KEY (id)
)


-- Table: public.kobodata_fotokobo

-- DROP TABLE IF EXISTS public.kobodata_fotokobo;

CREATE TABLE IF NOT EXISTS public.kobodata_fotokobo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    imagem character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    highlighted boolean NOT NULL,
    CONSTRAINT kobodata_foto_pkey PRIMARY KEY (id)
)

-- Table: public.kobodata_iniciativakobo_fotos

-- DROP TABLE IF EXISTS public.kobodata_iniciativakobo_fotos;

CREATE TABLE IF NOT EXISTS public.kobodata_iniciativakobo_fotos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    iniciativakobo_id bigint NOT NULL,
    fotokobo_id bigint NOT NULL,
    CONSTRAINT kobodata_iniciativa_fotos_pkey PRIMARY KEY (id),
    CONSTRAINT kobodata_iniciativa_fotos_iniciativa_id_foto_id_2634547e_uniq UNIQUE (iniciativakobo_id, fotokobo_id),
    CONSTRAINT kobodata_iniciativa__fotokobo_id_4fa92a42_fk_kobodata_ FOREIGN KEY (fotokobo_id)
        REFERENCES public.kobodata_fotokobo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT kobodata_iniciativak_iniciativakobo_id_ae272731_fk_kobodata_ FOREIGN KEY (iniciativakobo_id)
        REFERENCES public.kobodata_iniciativakobo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)
